const locationPlaces = [
    {place: "Costa Rica"},
    {place: "Walmart"},
    {place: "Springfield"},
    {place: "Petco"},
    {place: "Sam's Club Reef"},
    {place: "Ole Dan's boat wreck"},
    {place: "Jimmy's big boi fishin' spot"},
    {place: "Young Dan's boat wreck"},
    {place: "South Africa"},
    {place: "Croatia"},
    {place: "Blue Hole"},
    {place: "Brazil"},
    {place: "Antiqua"},
    {place: "Bahamas"},
    {place: "Orlando, FL"},
    {place: "San Jose, CA"},
    {place: "Destin, FL"},
    {place: "Argentina"},
    {place: "Honolulu, HI"},
    {place: "Wally World"},
    {place: "Lake Canada"},
    {place: "Friend's Place"},
    {place: "Philippines"},
    {place: "Madagascar"},
    {place: "Southern Japan"},
    {place: "Rarotonga"},
    {place: "Indonesia"},
    {place: "Guam"},
    {place: "Deep Darkness"},
    {place: "Gerrys Air Balloon and Fish Emporium"},
    {place: "Lake"},
    {place: "P. Sherman, 42 Wallaby Way, Sydney"},
    {place: "Pizza Planet"},
    {place: "Seaward reefs in the pacific ocean"},
    {place: "Coral reef in the western Pacific ocean"},
    {place: "A clear lagoon"},
    {place: "Coral and rubble areas"},
    {place: "Deep lagoon"},
    {place: "Over Yonder"},
    {place: "Down Under"},
    {place: "Sandy Castles Resort"},
    {place: "Navy Pier"}

]

export const nameLocation = () => {
    return locationPlaces.slice()
}