const tipList = [
    {p: "Feed your fish daily"},
    {p: "Talk to your fish about vacation before leaving"},
    {p: "Properly cycle the tank"},
    {p: "Acclimate them"},
    {p: "Ensure plenty of room"},
    {p: "Keep them apart"},
    {p: "Proper food"},
    {p: "Keep an eye on the water"},
    {p: "Clean everything"},
    {p: "Keep the peace"},
    {p: "Look out for sickness"},
    {p: "Act quickly"},
    {p: "pH Level"},
    {p: "Nitrites"},
    {p: "Nitrates"},
    {p: "KH"},
    {p: "Algae"},
    {p: "Kill them"},
    {p: "Insight is free"},
    {p: "Give no power"},
    {p: "Go into the unknown"},
    {p: "Library card"},
    {p: "Spend time with fish people"},
    {p: "Be skeptical"},
    {p: "Fight for what matters"},
    {p: "Find a method that works"},
    {p: "Join a movement"},
    {p: "Drink your coffee black"},
    {p: "Don't photoshop"},
    {p: "Read more"},
    {p: "Get used to feeling stupid"},
    {p: "Watch how they behave"},
    {p: "Learn something"},
    {p: "Find fish that inspire you"},
    {p: "Starve them if they misbehave"},
    {p: "See if they can survive on little"},
    {p: "Be successful"},
    {p: "Do what you'll say you'll do"},
    {p: "Be comfortable with abandonment"},
    {p: "Learn a new language"},
    {p: "Eat more protein"},
    {p: "Get people to tell you the truth"},
    {p: "Genius gets you nowhere. Execution is everything"},
    {p: " If given the choice of equity or cash, almost always take cash"},
    {p: "Meet new people as often as possible. Offer to help them"},
    {p: "Don’t discriminate. Connect anyone in your network to anyone else"},
    {p: "If you can’t do a pull-up, you have a problem"},
    {p: "Nobody likes a know-it-all"},
    {p: "Get a passport"},
    {p: "Quit your horrible job"},
    {p: "Read biographies"},
    {p: "Go to bed"},
    {p: "Wake up"},
    {p: "Scare yourself everyday"},
    {p: "Learn to climb trees"},
    {p: "Don't buy a lot of stuff"},
    {p: "Be humble"},
    {p: "Be curious"},
    {p: "Don't worry about Twitter followers"}
]

export const inputTips = () => {
    return tipList.slice()
}